### ISSUE TITLE
A value of type ‘PackIconMaterial’ cannot be added to[...] of type ‘UIElementCollection’

### ISSUE THREAD

**Issue by r0si** [MahApps/MahApps.Metro.IconPacks#112]
I get a error message in VS designer when trying to add a icon from the pack.
A „System.Windows.Markup.XamlParseException - Could not load file or assembly ControlEx, Version=3.0.2.4...“ is thrown when building the app.

Using VS 2017 Professional, C#7, Metro Alpha v2.0.0 -0186, IconPacks v2.3.0 and ControlEx v4.0.0 -0218.

App.xaml and MainWindow.xaml changed according to the Quick Start guide.

**Comment by Jacob-JA-Shanks** [comment]
Having a similar problem. Tried to use an icon from the modern pack on a WPF project (.NET 4.7.2). Followed the guide but noticed the VS was giving me a warning saying iconPacks:Modern couldn't be found in this context. Then running the program anyway yields the same error as shown below:

System.Windows.Markup.XamlParseException
  HResult=0x80131501
  Message=Could not load file or assembly 'ControlzEx, Version=3.0.2.4, Culture=neutral, PublicKeyToken=null' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)
  Source=PresentationFramework
  StackTrace:
   at System.Windows.Markup.WpfXamlLoader.Load(XamlReader xamlReader, IXamlObjectWriterFactory writerFactory, Boolean skipJournaledProperties, Object rootObject, XamlObjectWriterSettings settings, Uri baseUri)
   at System.Windows.Markup.WpfXamlLoader.LoadBaml(XamlReader xamlReader, Boolean skipJournaledProperties, Object rootObject, XamlAccessLevel accessLevel, Uri baseUri)
   at System.Windows.Markup.XamlReader.LoadBaml(Stream stream, ParserContext parserContext, Object parent, Boolean closeStream)
   at System.Windows.Application.LoadComponent(Object component, Uri resourceLocator)
   at Decaf.MainWindow.InitializeComponent() in C:\Users\jacob.shanks\Documents\Personal\Decaf\Decaf\MainWindow.xaml:line 1

Inner Exception 1:
FileLoadException: Could not load file or assembly 'ControlzEx, Version=3.0.2.4, Culture=neutral, PublicKeyToken=null' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)

**Comment by r0si** [comment]
Fixed it for me, thanks!

**Comment by Jacquers** [comment]
In my case I wanted a button with text and an icon. This did the trick:

<Button>
                <StackPanel Orientation="Horizontal">
                    <ContentControl VerticalAlignment="Center">
                        <iconPacks:MaterialLight Kind="Printer" />
                    </ContentControl>
                    <Label Content="Printing" />
                </StackPanel>
            </Button>
