### ISSUE TITLE
VS2022 WPF Designer Crashes Most Times with Icons

### ISSUE THREAD

**Issue by jstevenson72** [MahApps/MahApps.Metro.IconPacks#294]
Visual Studio 2022 WPF Designer fails to load, if I have included either Modern or Codicons in my UI.  With this error:

```
System.SystemException
System error.
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.VisualStudio.Telemetry.WindowsErrorReporting.WatsonReport.GetClrWatsonExceptionInfo(Exception exceptionObject)

System.AggregateException
System.Windows.Markup.XamlParseException: 'Cannot create unknown type '{http://metro.mahapps.com/winfx/xaml/iconpacks}Modern'.' Line number '277' and line position '45'. ---> System.Xaml.XamlObjectWriterException: 'Cannot create unknown type '{http://metro.mahapps.com/winfx/xaml/iconpacks}Modern'.' Line number '277' and line position '45'.
   at System.Xaml.XamlObjectWriter.WriteStartObject(XamlType xamlType)
   at System.Windows.FrameworkTemplate.LoadTemplateXaml(XamlReader templateReader, XamlObjectWriter currentWriter)
   --- End of inner exception stack trace ---
   at System.Windows.Markup.XamlReader.RewrapException(Exception e, IXamlLineInfo lineInfo, Uri baseUri)
   at System.Windows.FrameworkTemplate.LoadTemplateXaml(XamlReader templateReader, XamlObjectWriter currentWriter)
   at System.Windows.FrameworkTemplate.LoadTemplateXaml(XamlObjectWriter objectWriter)
   at System.Windows.FrameworkTemplate.LoadOptimizedTemplateContent(DependencyObject container, IComponentConnector componentConnector, IStyleConnector styleConnector, List`1 affectedChildren, UncommonField`1 templatedNonFeChildrenField)
   at System.Windows.FrameworkTemplate.LoadContent(DependencyObject container, List`1 affectedChildren)
   at System.Windows.StyleHelper.ApplyTemplateContent(UncommonField`1 dataField, DependencyObject container, FrameworkElementFactory templateRoot, Int32 lastChildIndex, HybridDictionary childIndexFromChildID, FrameworkTemplate frameworkTemplate)
   at System.Windows.FrameworkTemplate.ApplyTemplateContent(UncommonField`1 templateDataField, FrameworkElement container)
   at System.Windows.FrameworkElement.ApplyTemplate()
   at System.Windows.FrameworkElement.MeasureCore(Size availableSize)
   at System.Windows.UIElement.Measure(Size availableSize)
   at ActiproSoftware.Windows.Controls.Docking.Primitives.SplitContainerPanel.MeasureOverride(Size availableSize)
   at System.Windows.FrameworkElement.MeasureCore(Size availableSize)
   at System.Windows.UIElement.Measure(Size availableSize)
   at System.Windows.Controls.Control.MeasureOverride(Size constraint)
   at System.Windows.FrameworkElement.MeasureCore(Size availableSize)
   at System.Windows.UIElement.Measure(Size availableSize)
   at ActiproSoftware.Windows.Controls.Docking.Primitives.SplitContainerPanel.w0T(Size  )
   at ActiproSoftware.Windows.Controls.Docking.Primitives.SplitContainerPanel.MeasureOverride(Size availableSize)
   at System.Windows.FrameworkElement.MeasureCore(Size availableSize)
   at System.Windows.UIElement.Measure(Size availableSize)
   at System.Windows.Controls.Control.MeasureOverride(Size constraint)
   at System.Windows.FrameworkElement.MeasureCore(Size availableSize)
   at System.Windows.UIElement.Measure(Size availableSize)
   at ActiproSoftware.Windows.Controls.Docking.Primitives.SplitContainerPanel.w0T(Size  )
   at ActiproSoftware.Windows.Controls.Docking.Primitives.SplitContainerPanel.MeasureOverride(Size availableSize)
   at System.Windows.FrameworkElement.MeasureCore(Size availableSize)
   at System.Windows.UIElement.Measure(Size availableSize)
   at System.Windows.Controls.Control.MeasureOverride(Size constraint)
   at System.Windows.FrameworkElement.MeasureCore(Size availableSize)
   at System.Windows.UIElement.Measure(Size availableSize)
   at System.Windows.Controls.Grid.MeasureOverride(Size constraint)
   at System.Windows.FrameworkElement.MeasureCore(Size availableSize)
   at System.Windows.UIElement.Measure(Size availableSize)
   at System.Windows.ContextLayoutManager.UpdateLayout()
   at Microsoft.VisualStudio.DesignTools.WpfTap.WpfVisualTreeService.LiveMarkup.TapInstanceManager.GetFrameworkElementNameScope(DependencyObject ancestor)
   at Microsoft.VisualStudio.DesignTools.WpfTap.WpfVisualTreeService.LiveMarkup.TapInstanceManager.UpdateNameRegistration(TapInstanceBuilderContext context, XamlAction xamlAction)
   at Microsoft.VisualStudio.DesignTools.WpfTap.WpfVisualTreeService.LiveMarkup.TapInstanceManager.ProcessCurrentThreadActions(TapInstanceBuilderContext context)
   at Microsoft.VisualStudio.DesignTools.WpfTap.WpfVisualTreeService.LiveMarkup.TapInstanceManager.UpdateInstances(TapInstanceBuilderContext context)
   at Microsoft.VisualStudio.XSurface.Wpf.DesignerTapInstanceManager.UpdateInstances(TapInstanceBuilderContext context)
   at Microsoft.VisualStudio.XSurface.Wpf.Tap.SurfaceService.InstanceBuildDocumentInternal(Int32 documentId, Object rootObject)
   at Microsoft.VisualStudio.XSurface.Wpf.Tap.SurfaceService.HandleCreateSurfaceInternal(CreateSurfaceRequestInfo requestInfo)
   at Microsoft.VisualStudio.DesignTools.RuntimeHost.TapOM.ResponseWithError.ThrowIfFailed()
   at Microsoft.VisualStudio.DesignTools.SurfaceDesigner.Documents.SurfaceIsolation.DesignerInstanceManager.<BuildDocumentAsync>d__56.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.DesignTools.XamlSurfaceDesigner.Views.IsolatedSurfaceImageHost.<CreateSurfaceAsync>d__67.MoveNext()

System.AggregateException
One or more errors occurred.
```

I have the latest 4.11 NuGet Package with all Icon Packs installed in my solution.  Importing this namespace:
```
xmlns:iconPacks="http://metro.mahapps.com/winfx/xaml/iconpacks"
```
And using the icons in this way:
```
<Button
                    x:Name="MaximizeButton"
                    Click="MaximizeButton_Click"
                    Content="{iconPacks:Modern Kind=WindowMaximize}"
                    Foreground="{StaticResource Brush_Color_8}"
                    Style="{StaticResource ButtonWindowControl}"
                    ToolTip="{x:Static com:Strings.Maximize}"
                    Visibility="Collapsed"
                    WindowChrome.IsHitTestVisibleInChrome="True" />
```

**To Reproduce**
1. Add the complete NuGet Package
2. Add an Icon to a WPF 4.8 project as either a Markup Extension or the Image Source type to a Control Style/Template.
3. WPF Designer will initially work, but eventually crash

**Expected behavior**
No Error, Designer should work

**Screenshots**
![image](https://user-images.githubusercontent.com/1573442/165672434-3faff75f-7da4-41e7-b895-c1131e043b9a.png)

![image](https://user-images.githubusercontent.com/1573442/165672439-f43570a9-8c92-4304-ba50-3c742389154c.png)

**Desktop Environment (please complete the following information):**
 - IconPacks Version: 4.11
 - Visual Studio: 2022
 - .NET Framework: 4.8

**Repo**

**Additional context**

**Comment by punker76** [comment]
@jstevenson72 Idk what's really going on here. Maybe it's the `ButtonWindowControl`?

I created an app with .NET 4.8 and added your Button without the `ButtonWindowControl` and the designer seems to work as expected.

Microsoft Visual Studio Enterprise 2022 (64-bit) - Current
Version 17.3.1

![image](https://user-images.githubusercontent.com/658431/189652797-652f7574-4bde-4002-9528-ac67f87f91ae.png)

**Comment by seb30** [comment]
Updating to 17.3.3 helped in my case (or was it 17.3.2?). The designer is now usable.

**Comment by jstevenson72** [comment]
I'm on 17.3.2 now and the problem is no longer happening.  I assume MS screwed up the Designer for a while.
